### PR TITLE
Made spdlog a submodule that will be synched automatically by cmake

### PR DESCRIPTION
**Pull request by ugermann**
This is in response to #83. To facilitate future upgrades to spdlog, spdlog is now a git submodule.
I've changed the main CMakeLists.txt (for marian-train) so that it initialises and updates the submodule when cmake is run.

Please test before merging and report back.

### CODE REVIEW

**Comment by emjotde** [comment]
I am currently travelling, so give me a few days to take a look at that.

**Comment by ugermann** [comment]
@tomekd Does Marian now compile on GCC7 (Arch Linux)?

**Comment by tomekd** [comment]
@ugermann : yes, it does. Marian is safe until Ubuntu 20.04 now.

I had problems with getting spdlog by cmake. I had to run the command manually.

Tested on: gcc (GCC) 7.1.1 20170621, Boost 1.64.0-3

**Comment by snukky** [comment]
Please, do not use tabs for indentation. See [contrib/README](https://github.com/marian-nmt/marian-train/blob/master/contrib/README.md).

**Comment by ugermann** [comment]
@snukky: Where am I using tabs?

**Comment by tomekd** [comment]
Fix confirmed. Auto fetch is working now.

**Comment by snukky** [comment]
@ugermann In these commits, only in .gitmodules file. Previously here https://github.com/marian-nmt/marian-train/commit/a0857588e0650007752995f76cd5323c76e3fb9d, fixed here https://github.com/marian-nmt/marian-train/commit/0cf192fbfbcf93018db8bb0e9c44a08907be7ca5. Maybe just missed out IDE configuration?

**Comment by emjotde** [comment]
How does this relate to the marian-train repo from which I update the marian version?

**Comment by ugermann** [comment]
@snukky. As for the tabs in actual Marian code, this was obviously unintentional. The file .gitmodules was written by the git command line tool (via git submodule init), which apparently has tabs hardcoded. In order to fix this we'd have to set up git filters to fix things pre-commit, which I frankly think is overkill.

**Comment by ugermann** [comment]
Marian is  currently tracking branch amunmt-stable. To switch to the master
branch:

In the marian checkout:

```
git submodule deinit -f src/marian
```

edit .gitmodules and change the branch for marian to master

```
mkdir build
cd build
cmake ..
```

This will fail (due to marian-train commit commit 0af7727), but now you've
got marian-train checked out in src/marian.
Copy ../src/marian/VERSION to ../ (i.e., the root of the marian (formerly
amunmt) repo.

```
cmake ..
```

Should work now. Builds successfully on gna.

**Comment by emjotde** [comment]
I am working on updating amunmt-stable. I would rather keep a special branch for that.

**Comment by ugermann** [comment]
That's up to you. I only gave instruction on how to switch branches if you wanted to. The spdlog update was for @tomekd who couldn't compile on his setup (see #83).

**Pull request merged**
